on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  schedule:
    - cron: "5 4 * */1 *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Upload"
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name 'github-actions[bot]'
          git add . && git commit -m "Automatically updated dictionaries [skip ci]" && git push
